# fastly hdm
set -Ux FASTLY_API_KEY
set -Ux FASTLY_API_TOKEN $FASTLY_API_KEY
set -Ux FASTLY_CORP_KEY

set -Ux GITHUB_TOKEN

set -Ux BURDEN_API_KEY
set -Ux HUBCAP_API_KEY

set -gx GHIDRAH_API_KEY
set -gx GHIDRAH_FEATURE

set -Ux INFRI_DEV yafrank
set -Ux INFRI_FILE_ENC_KEY
set -Ux INFRI_VAULT_PASSWORD
set -Ux INFRI_VAULT_PASSWORD_DEV

set -Ux ANSIBLE_VAULT_PASSWORD
set -Ux SEM3_ANSIBLE_VAULT_PASSWORD
set -Ux VAULT_ADDR https://vault.hearstapps.com

set -Ux REGISTRY_HOST

set -Ux WIZ_CLIENT_ID
set -Ux WIZ_CLIENT_SECRET
