- name: Setup play machine
  hosts: localhost
  tasks:

    - ansible.builtin.include_role:
        name: roles/apt-packages

    - ansible.builtin.include_role:
        name: roles/nerdfonts

    - name: All the symlinks, get it done
      ansible.builtin.file:
        src: "{{ item[0] }}"
        dest: "{{ item[1] }}"
        owner: cmac4603
        group: cmac4603
        state: link
        force: true
      loop:
        - ['~/repos/dotfiles/alacritty-play.toml', '~/.config/alacritty/alacritty.toml']
        - ['~/repos/dotfiles/tmux-cfg', '~/.config/tmux']
        - ['~/repos/dotfiles/nvim', '~/.config/nvim']
        - ['~/repos/dotfiles/.gitconfig-play', '~/.gitconfig']
        - ['~/repos/dotfiles/fish/conf.d/exports.fish', '~/.config/fish/conf.d/exports.fish']
        - ['~/repos/dotfiles/fish/conf.d/fnm.fish', '~/.config/fish/conf.d/fnm.fish']
        - ['~/repos/dotfiles/fish/conf.d/kb_shortcuts.fish', '~/.config/fish/conf.d/kb_shortcuts.fish']
        - ['~/repos/dotfiles/fish/conf.d/stern.fish', '~/.config/fish/conf.d/stern.fish']
        - ['~/repos/dotfiles/fish/functions/fish_user_key_bindings.fish', '~/.config/fish/functions/fish_user_key_bindings.fish']
