- name: Setup play machine
  hosts: localhost
  tasks:

    - name: All the symlinks, get it done
      ansible.builtin.file:
        src: "{{ item[0] }}"
        dest: "{{ item[1] }}"
        owner: cmac4603
        group: cmac4603
        state: link
        force: true
      loop:
        - ['~/repos/dotfiles/alacritty-play.toml', '~/.config/alacritty/alacritty.toml']
        - ['~/repos/dotfiles/tmux-cfg', '~/.config/tmux']
        - ['~/repos/dotfiles/nvim', '~/.config/nvim']
        - ['~/repos/dotfiles/.gitconfig-play', '~/.gitconfig']
